name: Databricks Bundle CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  # ---------------------------------------------------------
  # 1. Validate bundle for Pull Requests
  # ---------------------------------------------------------
  validate:
    name: Validate Bundle
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate bundle
        working-directory: ./Day_9_Assignment/Day_9_vs
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks bundle validate -t dev


  # ---------------------------------------------------------
  # 2. Deploy bundle to PROD after merge to main
  # ---------------------------------------------------------
  deploy-prod:
    name: Deploy Bundle to Prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    # GitHub Environment
    environment: prod

    # Required for GitHub OIDC
    permissions:
      id-token: write
      contents: read

    env:
      # Databricks OIDC authentication
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Prod Bundle
        working-directory: ./Day_9_Assignment/Day_9_vs
        run: |
          databricks bundle validate -t prod

      - name: Deploy Bundle to Prod
        working-directory: ./Day_9_Assignment/Day_9_vs
        run: |
          databricks bundle deploy -t prod
